export const SAVE_CAMERA_ID = "SAVE_CAMERA_ID";
export const LOAD_PROPS = "LOAD_PROPS";
export const LOAD_SINGLE_PROP = "LOAD_PROPS";
export const PROPERTY_CHANGE = "PROPERTY_CHANGE";


export const TRIGGER_ANCHORS = "TRIGGER_ANCHORS";
export const ANCHOR_MOVED = "ANCHOR_MOVED";

