export const SAVE_CAMERA_ID = "SAVE_CAMERA_ID";
export const LOAD_PROPS = "LOAD_PROPS";
export const LOAD_SINGLE_PROP = "LOAD_PROPS";
export const PROPERTY_CHANGE = "PROPERTY_CHANGE";


export const TRIGGER_ANCHORS = "TRIGGER_ANCHORS";
export const ANCHOR_MOVED = "ANCHOR_MOVED";

export const SLIDER_CHANGED = "SLIDER_CHANGED";
export const SLIDER_MOVED = "SLIDER_MOVED";

export const LINE_NUM_CHANGED = "LINE_NUM_CHANGED";

export const CAMERA_STATUS_UPDATED = "CAMERA_STATUS_UPDATED";
export const LOGS_UPDATE = "LOGS_UPDATE";

